## Disable serial and UART interface.
CONFIG_SERIAL=n
CONFIG_UART_CONSOLE=n

CONFIG_LOG=n

CONFIG_NRF_802154_SER_RADIO=y
CONFIG_NRF_802154_TEMPERATURE_UPDATE=n

CONFIG_NRF_802154_SL_OPENSOURCE=y

CONFIG_RESET_ON_FATAL_ERROR=n
CONFIG_ASSERT=y